name: Magika
main: ru.iamdvz.magika.Magika
version: '${version}'
api-version: "1.18"
softdepend: [MagicSpells]
authors: [iamDvz]
description: "Made with love by iamDvz#2005. From magician to magicians."